# This is a basic workflow to help you get started with Actions

name: Main CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windowns-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Runs a single command using the runners shell
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version:  1.8

      # Runs a set of commands using the runners shell
      - name: Build with Gradle
        run: ./gradlew build
      
      # Runs the debug apk updload
      - name: Build Debug APK
        uses: actions/upload-artifact@v2.2.2
        with:
          name: app-debug
          path: app/build/outputs/debug/app-debug.apk  
